class ApiConstant:
    class Http:
        OK = 200
        CREATED = 201
        BAD_REQUEST = 400
        UNAUTHORIZED = 401
        FORBIDDEN = 403
        NOT_FOUND = 404
        METHOD_NOT_ALLOWED = 405
        INTERNAL_SERVER_ERROR = 500
        SERVICE_UNAVAILIABLE = 503

    class Errors:
        INVALID_DATA_TYPE = 'INVALID_DATA_TYPE'
        UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION'
        MULTIPLE_UNIQUE_CONSTRAINT_VIOLATION = 'MULTIPLE_UNIQUE_CONSTRAINT_VIOLATION'
        FOREIGN_KEY_CONSTRAINT_VIOLATION = 'FOREIGN_KEY_CONSTRAINT_VIOLATION'
        MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD'
        INVALID_FIELD_VALUE = 'INVALID_FIELD_VALUE'
        NOT_FOUND_ON_TWITCH = 'NOT_FOUND_ON_TWITCH'
        SERVICE_UNAVAILIABLE = 'SERVICE_UNAVAILIABLE'
        VALUE_NOT_ALLOWED = 'VALUE_NOT_ALLOWED'
        MUTTIPLE_VALUE_NOT_ALLOWED = 'MUTTIPLE_VALUE_NOT_ALLOWED'
        NOT_FOUND = 'NOT_FOUND'
        BAD_REQUEST = 'BAD_REQUEST'
        UNAUTHORIZED = 'UNAUTHORIZED'
        FORBIDDEN = 'FORBIDDEN'
